/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppGraphRouteImport } from './routes/_authenticated/app/graph'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app/profile'
import { Route as AuthenticatedAppReflectRouteImport } from './routes/_authenticated/app/reflect'
import { Route as AuthenticatedAppTimelineRouteImport } from './routes/_authenticated/app/timeline'
import { Route as AuthenticatedAppUniverseRouteImport } from './routes/_authenticated/app/universe'
import { Route as AuthenticatedAppSectionsSectionIdRouteImport } from './routes/_authenticated/app/sections/$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppGraphRoute = AuthenticatedAppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReflectRoute = AuthenticatedAppReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTimelineRoute =
  AuthenticatedAppTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppUniverseRoute =
  AuthenticatedAppUniverseRouteImport.update({
    id: '/universe',
    path: '/universe',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSectionsSectionIdRoute =
  AuthenticatedAppSectionsSectionIdRouteImport.update({
    id: '/sections/$sectionId',
    path: '/sections/$sectionId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/app/graph': typeof AuthenticatedAppGraphRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/reflect': typeof AuthenticatedAppReflectRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/app/universe': typeof AuthenticatedAppUniverseRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/sections/$sectionId': typeof AuthenticatedAppSectionsSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/graph': typeof AuthenticatedAppGraphRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/reflect': typeof AuthenticatedAppReflectRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/app/universe': typeof AuthenticatedAppUniverseRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/sections/$sectionId': typeof AuthenticatedAppSectionsSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/app/graph': typeof AuthenticatedAppGraphRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/reflect': typeof AuthenticatedAppReflectRoute
  '/_authenticated/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/_authenticated/app/universe': typeof AuthenticatedAppUniverseRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/sections/$sectionId': typeof AuthenticatedAppSectionsSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/reset-password'
    | '/app'
    | '/app/graph'
    | '/app/profile'
    | '/app/reflect'
    | '/app/timeline'
    | '/app/universe'
    | '/app/'
    | '/app/sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/reset-password'
    | '/app/graph'
    | '/app/profile'
    | '/app/reflect'
    | '/app/timeline'
    | '/app/universe'
    | '/app'
    | '/app/sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/graph'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/reflect'
    | '/_authenticated/app/timeline'
    | '/_authenticated/app/universe'
    | '/_authenticated/app/'
    | '/_authenticated/app/sections/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/graph': {
      id: '/_authenticated/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AuthenticatedAppGraphRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reflect': {
      id: '/_authenticated/app/reflect'
      path: '/reflect'
      fullPath: '/app/reflect'
      preLoaderRoute: typeof AuthenticatedAppReflectRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/timeline': {
      id: '/_authenticated/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AuthenticatedAppTimelineRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/universe': {
      id: '/_authenticated/app/universe'
      path: '/universe'
      fullPath: '/app/universe'
      preLoaderRoute: typeof AuthenticatedAppUniverseRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/sections/$sectionId': {
      id: '/_authenticated/app/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/app/sections/$sectionId'
      preLoaderRoute: typeof AuthenticatedAppSectionsSectionIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppGraphRoute: typeof AuthenticatedAppGraphRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppReflectRoute: typeof AuthenticatedAppReflectRoute
  AuthenticatedAppTimelineRoute: typeof AuthenticatedAppTimelineRoute
  AuthenticatedAppUniverseRoute: typeof AuthenticatedAppUniverseRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppSectionsSectionIdRoute: typeof AuthenticatedAppSectionsSectionIdRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppGraphRoute: AuthenticatedAppGraphRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppReflectRoute: AuthenticatedAppReflectRoute,
  AuthenticatedAppTimelineRoute: AuthenticatedAppTimelineRoute,
  AuthenticatedAppUniverseRoute: AuthenticatedAppUniverseRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppSectionsSectionIdRoute:
    AuthenticatedAppSectionsSectionIdRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
